export default {
  projectName: 'game-shelf',
  branchPrefix: 'feat/',
  baseBranch: 'main',
  worktreeRoot: 'worktrees',
  packageDirs: ['.', 'server', 'worker', 'hltb-scraper', 'metacritic-scraper', 'psprices-scraper'],
  env: {
    exampleFile: '.env.example',
    localFile: '.env',
    sharedTemplateFile: '~/.config/game-shelf/worktree.env',
  },
  pr: {
    baseRef: 'origin/main',
    summaryOutputFile: '.pr-summary-prompt.md',
    agentOutputFile: '.pr-agent-prompt.md',
    excludedDiffPaths: [':(glob,exclude)**/package-lock.json', ':(glob,exclude)**/dist/**'],
    ciWorkflowName: 'CI PR Checks',
    coverageArtifactName: 'coverage-reports',
    verifyCommands: ['npm run lint', 'npm run test', 'npm run build'],
    additionalVerifyCommands: ['npm run test:backend', 'npm run test:backend:coverage'],
  },
  worktree: {
    adapterModule: 'scripts/worktree-dev.mjs',
    bootstrap: {
      installScript: 'ci:all',
    },
    runtime: {
      projectSlugPrefix: 'gameshelf',
      worktreeHintMaxLength: 24,
      maxPortOffset: 10000,
      ports: {
        FRONTEND_PORT: 8100,
        PWA_HOST_PORT: 8200,
        PWA_ROOT_CA_PORT: 8300,
        EDGE_HOST_PORT: 8080,
        API_HOST_PORT: 3000,
        POSTGRES_HOST_PORT: 5432,
        HLTB_HOST_PORT: 8788,
        METACRITIC_HOST_PORT: 8789,
        PSPRICES_HOST_PORT: 8790,
      },
    },
    env: {
      localFile: '.env',
      sharedTemplateFile: '~/.config/game-shelf/worktree.env',
      defaultSharedSecretsDir: '~/.config/game-shelf/nas-secrets',
    },
    compose: {
      files: ['docker-compose.yml', 'docker-compose.dev.yml'],
      projectNameEnvVar: 'COMPOSE_PROJECT_NAME',
      services: [
        'postgres',
        'hltb-scraper',
        'metacritic-scraper',
        'psprices-scraper',
        'api',
        'worker-general',
        'worker-recommendations',
        'edge',
      ],
      restartServices: [
        'edge',
        'worker-general',
        'worker-recommendations',
        'api',
        'postgres',
        'hltb-scraper',
        'metacritic-scraper',
        'psprices-scraper',
      ],
      logServices: [
        'edge',
        'worker-general',
        'worker-recommendations',
        'api',
        'postgres',
        'hltb-scraper',
        'metacritic-scraper',
        'psprices-scraper',
      ],
      startCommandHint: 'npm run dev:stack:up',
    },
    frontend: {
      prestartCommand: 'npm run prestart',
      serveCommand: 'npx ng serve',
      defaultHost: '127.0.0.1',
      externalHost: '0.0.0.0',
      proxyRoutes: {
        '/v1': 'API_HOST_PORT',
        '/manuals': 'EDGE_HOST_PORT',
      },
      localEnvironmentFile: 'src/environments/environment.local.ts',
      buildRoot: 'www/browser',
    },
    pwa: {
      prebuildCommand: 'npm run prebuild',
      buildCommand: 'npx ng build --configuration production',
      httpsServerScript: 'scripts/pwa-https-server.mjs',
      rootCaServerScript: 'scripts/pwa-root-ca-server.mjs',
      certDir: '.tmp/pwa-certs',
      certFileEnvVar: 'WORKTREE_PWA_CERT_FILE',
      keyFileEnvVar: 'WORKTREE_PWA_KEY_FILE',
      manualsPublicBaseUrl: null,
      pwaManualsPublicBaseUrl: '/manuals',
    },
    db: {
      seedPathEnvVar: 'DEV_DB_SEED_PATH',
      defaultSeedPath: '~/.cache/game-shelf/dev-db-seed/latest.sql.gz',
    },
  },
};
