name: Bug
description: Report a bug
labels: ['fix']

body:
  - type: textarea
    attributes:
      label: Description

  - type: textarea
    attributes:
      label: Steps to reproduce

  - type: textarea
    attributes:
      label: Expected behavior

  - type: input
    attributes:
      label: Suggested commit type
      description: Usually "fix"
