// This file is auto-generated by scripts/generate-metacritic-platform-artifacts.mjs.
// Do not edit manually.
const SUPPORTED_IGDB_PLATFORM_IDS = [
  5, 6, 8, 9, 11, 12, 20, 21, 24, 37, 38, 41, 46, 48, 49, 130, 137, 159, 167, 169, 508
] as const;

export const METACRITIC_SUPPORTED_IGDB_PLATFORM_IDS = new Set<number>(SUPPORTED_IGDB_PLATFORM_IDS);

export function isMetacriticPlatformSupported(platformIgdbId: number | null | undefined): boolean {
  return (
    typeof platformIgdbId === 'number' &&
    Number.isFinite(platformIgdbId) &&
    Number.isInteger(platformIgdbId) &&
    METACRITIC_SUPPORTED_IGDB_PLATFORM_IDS.has(platformIgdbId)
  );
}
