// This file is auto-generated by scripts/generate-mobygames-platform-artifacts.mjs.
// Do not edit manually.
const IGDB_TO_MOBYGAMES_PLATFORM_ENTRIES: ReadonlyArray<readonly [number, number]> = [
  [4, 9],
  [5, 82],
  [6, 3],
  [7, 6],
  [8, 7],
  [9, 81],
  [11, 13],
  [12, 69],
  [13, 2],
  [18, 22],
  [19, 15],
  [20, 44],
  [21, 14],
  [22, 11],
  [23, 8],
  [24, 12],
  [27, 57],
  [29, 16],
  [30, 21],
  [32, 23],
  [33, 10],
  [34, 91],
  [35, 25],
  [37, 101],
  [38, 46],
  [39, 86],
  [41, 132],
  [46, 105],
  [48, 141],
  [49, 142],
  [50, 35],
  [52, 143],
  [57, 48],
  [59, 28],
  [61, 18],
  [62, 17],
  [64, 26],
  [67, 30],
  [68, 29],
  [70, 37],
  [78, 20],
  [79, 36],
  [82, 84],
  [84, 114],
  [86, 40],
  [87, 38],
  [117, 73],
  [119, 52],
  [120, 53],
  [121, 106],
  [123, 49],
  [125, 94],
  [128, 127],
  [130, 203],
  [136, 54],
  [137, 174],
  [149, 95],
  [150, 45],
  [159, 87],
  [166, 152],
  [167, 288],
  [169, 289],
  [274, 59],
  [339, 103],
  [472, 323],
  [508, 333]
] as const;

export const IGDB_TO_MOBYGAMES_PLATFORM_ID_MAP = new Map<number, number>(
  IGDB_TO_MOBYGAMES_PLATFORM_ENTRIES
);

export function resolveMobyGamesPlatformId(
  platformIgdbId: number | null | undefined
): number | null {
  if (!Number.isInteger(platformIgdbId) || (platformIgdbId as number) <= 0) {
    return null;
  }

  return IGDB_TO_MOBYGAMES_PLATFORM_ID_MAP.get(platformIgdbId as number) ?? null;
}
