import { Pool } from 'pg';

export const MIGRATIONS: string[] = [
  `
  CREATE EXTENSION IF NOT EXISTS vector;
  `,
  `
  CREATE TABLE IF NOT EXISTS games (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS views (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS sync_events (
    event_id BIGSERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    operation TEXT NOT NULL,
    payload JSONB,
    server_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS sync_events_cursor_idx
  ON sync_events (event_id);
  `,
  `
  CREATE TABLE IF NOT EXISTS idempotency_keys (
    op_id TEXT PRIMARY KEY,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS image_assets (
    cache_key TEXT PRIMARY KEY,
    source_url TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS hltb_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS metacritic_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS mobygames_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    platform TEXT,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_runs (
    id BIGSERIAL PRIMARY KEY,
    target TEXT NOT NULL CHECK (target IN ('BACKLOG', 'WISHLIST')),
    status TEXT NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    triggered_by TEXT NOT NULL CHECK (triggered_by IN ('manual', 'scheduler', 'stale-read')),
    settings_hash TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    error TEXT
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_runs_target_status_started_idx
  ON recommendation_runs (target, status, started_at DESC);
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendations (
    run_id BIGINT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
    runtime_mode TEXT NOT NULL DEFAULT 'NEUTRAL' CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    rank INTEGER NOT NULL,
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    score_total NUMERIC NOT NULL,
    score_components JSONB NOT NULL,
    explanations JSONB NOT NULL,
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    CONSTRAINT recommendations_pkey PRIMARY KEY (run_id, runtime_mode, rank),
    CONSTRAINT recommendations_run_runtime_game_uid
      UNIQUE (run_id, runtime_mode, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  ALTER TABLE recommendations
  ADD COLUMN IF NOT EXISTS runtime_mode TEXT;
  `,
  `
  UPDATE recommendations
  SET runtime_mode = 'NEUTRAL'
  WHERE runtime_mode IS NULL;
  `,
  `
  ALTER TABLE recommendations
  ALTER COLUMN runtime_mode SET DEFAULT 'NEUTRAL';
  `,
  `
  ALTER TABLE recommendations
  ALTER COLUMN runtime_mode SET NOT NULL;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'recommendations_runtime_mode_check'
    ) THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_runtime_mode_check
      CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG'));
    END IF;
  END $$;
  `,
  `
  ALTER TABLE recommendations
  DROP CONSTRAINT IF EXISTS recommendations_run_id_igdb_game_id_platform_igdb_id_key;
  `,
  `
  ALTER TABLE recommendations
  DROP CONSTRAINT IF EXISTS recommendations_pkey;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'recommendations_pkey'
    ) THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_pkey
      PRIMARY KEY (run_id, runtime_mode, rank);
    END IF;
  END $$;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conname = 'recommendations_run_runtime_game_uid'
    ) THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_run_runtime_game_uid
      UNIQUE (run_id, runtime_mode, igdb_game_id, platform_igdb_id);
    END IF;
  END $$;
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendations_run_mode_rank_idx
  ON recommendations (run_id, runtime_mode, rank);
  `,
  `
  CREATE TABLE IF NOT EXISTS game_similarity (
    source_igdb_game_id TEXT NOT NULL,
    source_platform_igdb_id INTEGER NOT NULL,
    similar_igdb_game_id TEXT NOT NULL,
    similar_platform_igdb_id INTEGER NOT NULL,
    similarity NUMERIC NOT NULL,
    reasons JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (source_igdb_game_id, source_platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    FOREIGN KEY (similar_igdb_game_id, similar_platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (
      source_igdb_game_id,
      source_platform_igdb_id,
      similar_igdb_game_id,
      similar_platform_igdb_id
    )
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS game_similarity_source_similarity_idx
  ON game_similarity (source_igdb_game_id, source_platform_igdb_id, similarity DESC);
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_lanes (
    run_id BIGINT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
    runtime_mode TEXT NOT NULL CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    lane TEXT NOT NULL CHECK (lane IN ('overall', 'hiddenGems', 'exploration')),
    rank INTEGER NOT NULL,
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    score_total NUMERIC NOT NULL,
    score_components JSONB NOT NULL,
    explanations JSONB NOT NULL,
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (run_id, runtime_mode, lane, rank),
    UNIQUE (run_id, runtime_mode, lane, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_lanes_run_mode_lane_rank_idx
  ON recommendation_lanes (run_id, runtime_mode, lane, rank);
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_history (
    target TEXT NOT NULL CHECK (target IN ('BACKLOG', 'WISHLIST')),
    runtime_mode TEXT NOT NULL CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    recommendation_count INTEGER NOT NULL DEFAULT 0,
    last_recommended_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (target, runtime_mode, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_history_target_mode_last_idx
  ON recommendation_history (target, runtime_mode, last_recommended_at DESC);
  `,
  `
  CREATE TABLE IF NOT EXISTS game_embeddings (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    embedding vector(1536) NOT NULL,
    embedding_model TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id),
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS game_embeddings_vector_idx
  ON game_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);
  `
];

export async function createPool(databaseUrl: string): Promise<Pool> {
  const pool = new Pool({
    connectionString: databaseUrl,
    max: 12,
    idleTimeoutMillis: 30_000
  });
  // Keep the API process alive when Postgres restarts and idle clients are terminated.
  pool.on('error', (error: Error) => {
    console.warn('[db] pool_client_error', {
      message: error.message,
      code: (error as { code?: unknown }).code ?? null
    });
  });

  const client = await pool.connect();

  try {
    await runMigrations(client);
  } finally {
    client.release();
  }

  return pool;
}

export async function runMigrations(client: {
  query: (sql: string) => Promise<unknown>;
}): Promise<void> {
  for (const migration of MIGRATIONS) {
    await client.query(migration);
  }
}
