import { Pool } from 'pg';

export const MIGRATIONS: string[] = [
  `
  CREATE EXTENSION IF NOT EXISTS vector;
  `,
  `
  CREATE TABLE IF NOT EXISTS games (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS views (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS sync_events (
    event_id BIGSERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    operation TEXT NOT NULL,
    payload JSONB,
    server_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS sync_events_cursor_idx
  ON sync_events (event_id);
  `,
  `
  CREATE TABLE IF NOT EXISTS idempotency_keys (
    op_id TEXT PRIMARY KEY,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS image_assets (
    cache_key TEXT PRIMARY KEY,
    source_url TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS hltb_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS fcm_tokens (
    token TEXT PRIMARY KEY,
    platform TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    timezone TEXT,
    app_version TEXT,
    user_agent TEXT,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS metacritic_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS release_watch_state (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    last_known_release_marker TEXT,
    last_known_release_precision TEXT NOT NULL DEFAULT 'unknown',
    last_known_release_date DATE,
    last_known_release_year INTEGER,
    last_seen_state TEXT NOT NULL DEFAULT 'unknown',
    last_igdb_refresh_at TIMESTAMPTZ,
    last_hltb_refresh_at TIMESTAMPTZ,
    last_metacritic_refresh_at TIMESTAMPTZ,
    next_check_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_notified_set_at TIMESTAMPTZ,
    last_notified_change_at TIMESTAMPTZ,
    last_notified_unset_at TIMESTAMPTZ,
    last_notified_release_day DATE,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS release_watch_state_next_check_idx
  ON release_watch_state (next_check_at);
  `,
  // Backfill columns for existing deployments created before release_watch_state schema expansion.
  `
  ALTER TABLE release_watch_state
  ADD COLUMN IF NOT EXISTS last_known_release_marker TEXT;
  `,
  `
  ALTER TABLE release_watch_state
  ADD COLUMN IF NOT EXISTS last_known_release_precision TEXT NOT NULL DEFAULT 'unknown';
  `,
  `
  ALTER TABLE release_watch_state
  ADD COLUMN IF NOT EXISTS last_metacritic_refresh_at TIMESTAMPTZ;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'release_watch_state_release_precision_check'
        AND c.conrelid = 'release_watch_state'::regclass
    ) THEN
      ALTER TABLE release_watch_state
      ADD CONSTRAINT release_watch_state_release_precision_check
      CHECK (last_known_release_precision IN ('unknown', 'year', 'quarter', 'month', 'day'));
    END IF;
  END $$;
  `,
  `
  CREATE TABLE IF NOT EXISTS release_notification_log (
    id BIGSERIAL PRIMARY KEY,
    event_type TEXT NOT NULL,
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    event_key TEXT NOT NULL UNIQUE,
    payload JSONB NOT NULL,
    sent_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS mobygames_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    platform TEXT,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_runs (
    id BIGSERIAL PRIMARY KEY,
    target TEXT NOT NULL CHECK (target IN ('BACKLOG', 'WISHLIST', 'DISCOVERY')),
    status TEXT NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    triggered_by TEXT NOT NULL CHECK (triggered_by IN ('manual', 'scheduler', 'stale-read')),
    settings_hash TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    error TEXT
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_runs_target_status_started_idx
  ON recommendation_runs (target, status, started_at DESC);
  `,
  `
  DO $$
  BEGIN
    IF EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'recommendation_runs_target_check'
        AND c.conrelid = 'recommendation_runs'::regclass
    ) THEN
      ALTER TABLE recommendation_runs
      DROP CONSTRAINT recommendation_runs_target_check;
    END IF;
    ALTER TABLE recommendation_runs
      ADD CONSTRAINT recommendation_runs_target_check
      CHECK (target IN ('BACKLOG', 'WISHLIST', 'DISCOVERY'));
  END $$;
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendations (
    run_id BIGINT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
    runtime_mode TEXT NOT NULL DEFAULT 'NEUTRAL' CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    rank INTEGER NOT NULL,
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    score_total NUMERIC NOT NULL,
    score_components JSONB NOT NULL,
    explanations JSONB NOT NULL,
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    CONSTRAINT recommendations_pkey PRIMARY KEY (run_id, runtime_mode, rank),
    CONSTRAINT recommendations_run_runtime_game_uid
      UNIQUE (run_id, runtime_mode, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  ALTER TABLE recommendations
  ADD COLUMN IF NOT EXISTS runtime_mode TEXT;
  `,
  `
  UPDATE recommendations
  SET runtime_mode = 'NEUTRAL'
  WHERE runtime_mode IS NULL;
  `,
  `
  ALTER TABLE recommendations
  ALTER COLUMN runtime_mode SET DEFAULT 'NEUTRAL';
  `,
  `
  ALTER TABLE recommendations
  ALTER COLUMN runtime_mode SET NOT NULL;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'recommendations_runtime_mode_check'
        AND c.conrelid = 'recommendations'::regclass
    ) THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_runtime_mode_check
      CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG'));
    END IF;
  END $$;
  `,
  `
  ALTER TABLE recommendations
  DROP CONSTRAINT IF EXISTS recommendations_run_id_igdb_game_id_platform_igdb_id_key;
  `,
  `
  DO $$
  DECLARE
    existing_pkey_name TEXT;
    existing_pkey_def TEXT;
  BEGIN
    SELECT c.conname, pg_get_constraintdef(c.oid)
    INTO existing_pkey_name, existing_pkey_def
    FROM pg_constraint c
    WHERE c.conrelid = 'recommendations'::regclass
      AND c.contype = 'p'
    LIMIT 1;

    IF existing_pkey_name IS NULL THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_pkey
      PRIMARY KEY (run_id, runtime_mode, rank);
    ELSIF existing_pkey_def NOT LIKE 'PRIMARY KEY (run_id, runtime_mode, rank)%' THEN
      EXECUTE format('ALTER TABLE recommendations DROP CONSTRAINT %I', existing_pkey_name);
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_pkey
      PRIMARY KEY (run_id, runtime_mode, rank);
    ELSIF existing_pkey_name <> 'recommendations_pkey' THEN
      EXECUTE format(
        'ALTER TABLE recommendations RENAME CONSTRAINT %I TO recommendations_pkey',
        existing_pkey_name
      );
    END IF;
  END $$;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'recommendations_run_runtime_game_uid'
        AND c.conrelid = 'recommendations'::regclass
    ) THEN
      ALTER TABLE recommendations
      ADD CONSTRAINT recommendations_run_runtime_game_uid
      UNIQUE (run_id, runtime_mode, igdb_game_id, platform_igdb_id);
    END IF;
  END $$;
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendations_run_mode_rank_idx
  ON recommendations (run_id, runtime_mode, rank);
  `,
  `
  CREATE TABLE IF NOT EXISTS game_similarity (
    run_id BIGINT,
    target TEXT,
    runtime_mode TEXT,
    source_igdb_game_id TEXT NOT NULL,
    source_platform_igdb_id INTEGER NOT NULL,
    similar_igdb_game_id TEXT NOT NULL,
    similar_platform_igdb_id INTEGER NOT NULL,
    similarity NUMERIC NOT NULL,
    reasons JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (source_igdb_game_id, source_platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    FOREIGN KEY (similar_igdb_game_id, similar_platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (
      source_igdb_game_id,
      source_platform_igdb_id,
      similar_igdb_game_id,
      similar_platform_igdb_id
    )
  );
  `,
  `
  ALTER TABLE game_similarity
  ADD COLUMN IF NOT EXISTS run_id BIGINT;
  `,
  `
  ALTER TABLE game_similarity
  ADD COLUMN IF NOT EXISTS target TEXT;
  `,
  `
  ALTER TABLE game_similarity
  ADD COLUMN IF NOT EXISTS runtime_mode TEXT;
  `,
  `
  UPDATE game_similarity gs
  SET target = rr.target
  FROM recommendation_runs rr
  WHERE gs.target IS NULL
    AND gs.run_id IS NOT NULL
    AND rr.id = gs.run_id;
  `,
  `
  UPDATE game_similarity
  SET runtime_mode = 'NEUTRAL'
  WHERE runtime_mode IS NULL;
  `,
  `
  DELETE FROM game_similarity
  WHERE run_id IS NULL;
  `,
  `
  ALTER TABLE game_similarity
  ALTER COLUMN runtime_mode SET DEFAULT 'NEUTRAL';
  `,
  `
  ALTER TABLE game_similarity
  ALTER COLUMN runtime_mode SET NOT NULL;
  `,
  `
  ALTER TABLE game_similarity
  ALTER COLUMN target SET NOT NULL;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'game_similarity_target_check'
        AND c.conrelid = 'game_similarity'::regclass
    ) THEN
      ALTER TABLE game_similarity
      ADD CONSTRAINT game_similarity_target_check
      CHECK (target IN ('BACKLOG', 'WISHLIST', 'DISCOVERY'));
    END IF;
  END $$;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'game_similarity_runtime_mode_check'
        AND c.conrelid = 'game_similarity'::regclass
    ) THEN
      ALTER TABLE game_similarity
      ADD CONSTRAINT game_similarity_runtime_mode_check
      CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG'));
    END IF;
  END $$;
  `,
  `
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'game_similarity_run_fk'
        AND c.conrelid = 'game_similarity'::regclass
    ) THEN
      ALTER TABLE game_similarity
      ADD CONSTRAINT game_similarity_run_fk
      FOREIGN KEY (run_id)
      REFERENCES recommendation_runs(id)
      ON DELETE CASCADE;
    END IF;
  END $$;
  `,
  `
  ALTER TABLE game_similarity
  ALTER COLUMN run_id SET NOT NULL;
  `,
  `
  DO $$
  DECLARE
    existing_pkey_name TEXT;
    existing_pkey_def TEXT;
  BEGIN
    SELECT c.conname, pg_get_constraintdef(c.oid)
    INTO existing_pkey_name, existing_pkey_def
    FROM pg_constraint c
    WHERE c.conrelid = 'game_similarity'::regclass
      AND c.contype = 'p'
    LIMIT 1;

    IF existing_pkey_name IS NULL THEN
      ALTER TABLE game_similarity
      ADD CONSTRAINT game_similarity_pkey
      PRIMARY KEY (
        run_id,
        target,
        runtime_mode,
        source_igdb_game_id,
        source_platform_igdb_id,
        similar_igdb_game_id,
        similar_platform_igdb_id
      );
    ELSIF existing_pkey_def NOT LIKE 'PRIMARY KEY (run_id, target, runtime_mode, source_igdb_game_id, source_platform_igdb_id, similar_igdb_game_id, similar_platform_igdb_id)%' THEN
      EXECUTE format('ALTER TABLE game_similarity DROP CONSTRAINT %I', existing_pkey_name);
      ALTER TABLE game_similarity
      ADD CONSTRAINT game_similarity_pkey
      PRIMARY KEY (
        run_id,
        target,
        runtime_mode,
        source_igdb_game_id,
        source_platform_igdb_id,
        similar_igdb_game_id,
        similar_platform_igdb_id
      );
    ELSIF existing_pkey_name <> 'game_similarity_pkey' THEN
      EXECUTE format(
        'ALTER TABLE game_similarity RENAME CONSTRAINT %I TO game_similarity_pkey',
        existing_pkey_name
      );
    END IF;
  END $$;
  `,
  `
  DROP INDEX IF EXISTS game_similarity_source_similarity_idx;
  `,
  `
  CREATE INDEX IF NOT EXISTS game_similarity_run_mode_source_similarity_idx
  ON game_similarity (
    run_id,
    target,
    runtime_mode,
    source_igdb_game_id,
    source_platform_igdb_id,
    similarity DESC
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_lanes (
    run_id BIGINT NOT NULL REFERENCES recommendation_runs(id) ON DELETE CASCADE,
    runtime_mode TEXT NOT NULL CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    lane TEXT NOT NULL CHECK (lane IN ('overall', 'hiddenGems', 'exploration', 'blended', 'popular', 'recent')),
    rank INTEGER NOT NULL,
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    score_total NUMERIC NOT NULL,
    score_components JSONB NOT NULL,
    explanations JSONB NOT NULL,
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (run_id, runtime_mode, lane, rank),
    UNIQUE (run_id, runtime_mode, lane, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_lanes_run_mode_lane_rank_idx
  ON recommendation_lanes (run_id, runtime_mode, lane, rank);
  `,
  `
  DO $$
  BEGIN
    IF EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'recommendation_lanes_lane_check'
        AND c.conrelid = 'recommendation_lanes'::regclass
    ) THEN
      ALTER TABLE recommendation_lanes
      DROP CONSTRAINT recommendation_lanes_lane_check;
    END IF;
    ALTER TABLE recommendation_lanes
      ADD CONSTRAINT recommendation_lanes_lane_check
      CHECK (lane IN ('overall', 'hiddenGems', 'exploration', 'blended', 'popular', 'recent'));
  END $$;
  `,
  `
  CREATE TABLE IF NOT EXISTS recommendation_history (
    target TEXT NOT NULL CHECK (target IN ('BACKLOG', 'WISHLIST', 'DISCOVERY')),
    runtime_mode TEXT NOT NULL CHECK (runtime_mode IN ('NEUTRAL', 'SHORT', 'LONG')),
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    recommendation_count INTEGER NOT NULL DEFAULT 0,
    last_recommended_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE,
    PRIMARY KEY (target, runtime_mode, igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS recommendation_history_target_mode_last_idx
  ON recommendation_history (target, runtime_mode, last_recommended_at DESC);
  `,
  `
  DO $$
  BEGIN
    IF EXISTS (
      SELECT 1
      FROM pg_constraint c
      WHERE c.conname = 'recommendation_history_target_check'
        AND c.conrelid = 'recommendation_history'::regclass
    ) THEN
      ALTER TABLE recommendation_history
      DROP CONSTRAINT recommendation_history_target_check;
    END IF;
    ALTER TABLE recommendation_history
      ADD CONSTRAINT recommendation_history_target_check
      CHECK (target IN ('BACKLOG', 'WISHLIST', 'DISCOVERY'));
  END $$;
  `,
  `
  CREATE TABLE IF NOT EXISTS game_embeddings (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    embedding vector(1536) NOT NULL,
    embedding_model TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id),
    FOREIGN KEY (igdb_game_id, platform_igdb_id)
      REFERENCES games(igdb_game_id, platform_igdb_id)
      ON DELETE CASCADE
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS game_embeddings_vector_idx
  ON game_embeddings
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);
  `,
  `
  CREATE TABLE IF NOT EXISTS background_jobs (
    id BIGSERIAL PRIMARY KEY,
    job_type TEXT NOT NULL,
    dedupe_key TEXT,
    payload JSONB NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'succeeded', 'failed')),
    priority INTEGER NOT NULL DEFAULT 100,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    locked_by TEXT,
    locked_at TIMESTAMPTZ,
    last_error TEXT,
    result JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS background_jobs_pending_idx
  ON background_jobs (status, priority, available_at, id);
  `,
  `
  CREATE UNIQUE INDEX IF NOT EXISTS background_jobs_active_dedupe_idx
  ON background_jobs (dedupe_key)
  WHERE dedupe_key IS NOT NULL AND status IN ('pending', 'running');
  `,
  `
  CREATE INDEX IF NOT EXISTS background_jobs_terminal_finished_idx
  ON background_jobs (status, finished_at, id)
  WHERE status IN ('succeeded', 'failed') AND finished_at IS NOT NULL;
  `
];

export async function createPool(databaseUrl: string): Promise<Pool> {
  const pool = new Pool({
    connectionString: databaseUrl,
    max: 12,
    idleTimeoutMillis: 30_000
  });
  // Keep the API process alive when Postgres restarts and idle clients are terminated.
  pool.on('error', (error: Error) => {
    console.warn('[db] pool_client_error', {
      message: error.message,
      code: (error as { code?: unknown }).code ?? null
    });
  });

  const client = await pool.connect();

  try {
    await runMigrations(client);
  } finally {
    client.release();
  }

  return pool;
}

export async function runMigrations(client: {
  query: (sql: string) => Promise<unknown>;
}): Promise<void> {
  const toError = (value: unknown): Error =>
    value instanceof Error ? value : new Error(String(value));

  // Use a stable, namespaced key hashed by Postgres to avoid hard-coded magic numbers
  // and keep collision risk negligible for this app-specific migration lock.
  const migrationLockId = 'game-shelf:migrations:v1';
  const migrationLockIdSqlLiteral = migrationLockId.replace(/'/g, "''");
  const migrationLockSql = `SELECT pg_advisory_lock(hashtextextended('${migrationLockIdSqlLiteral}', 0));`;
  const migrationUnlockSql = `SELECT pg_advisory_unlock(hashtextextended('${migrationLockIdSqlLiteral}', 0));`;

  await client.query(migrationLockSql);

  let migrationError: Error | null = null;
  try {
    for (const migration of MIGRATIONS) {
      await client.query(migration);
    }
  } catch (error) {
    migrationError = toError(error);
  } finally {
    try {
      await client.query(migrationUnlockSql);
    } catch (unlockError) {
      const normalizedUnlockError = toError(unlockError);
      console.error('[db] migration_unlock_error', {
        message: normalizedUnlockError.message,
        originalMigrationError:
          migrationError instanceof Error ? { message: migrationError.message } : migrationError
      });

      if (!migrationError) {
        throw normalizedUnlockError;
      }
    }
  }

  if (migrationError) {
    throw migrationError;
  }
}
