import { Pool } from 'pg';

const MIGRATIONS: string[] = [
  `
  CREATE TABLE IF NOT EXISTS games (
    igdb_game_id TEXT NOT NULL,
    platform_igdb_id INTEGER NOT NULL,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (igdb_game_id, platform_igdb_id)
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS views (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS sync_events (
    event_id BIGSERIAL PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_key TEXT NOT NULL,
    operation TEXT NOT NULL,
    payload JSONB,
    server_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE INDEX IF NOT EXISTS sync_events_cursor_idx
  ON sync_events (event_id);
  `,
  `
  CREATE TABLE IF NOT EXISTS idempotency_keys (
    op_id TEXT PRIMARY KEY,
    result JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS image_assets (
    cache_key TEXT PRIMARY KEY,
    source_url TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS hltb_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `,
  `
  CREATE TABLE IF NOT EXISTS metacritic_search_cache (
    cache_key TEXT PRIMARY KEY,
    query_title TEXT NOT NULL,
    release_year INTEGER,
    platform TEXT,
    include_candidates BOOLEAN NOT NULL DEFAULT FALSE,
    response_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  `
];

export async function createPool(databaseUrl: string): Promise<Pool> {
  const pool = new Pool({
    connectionString: databaseUrl,
    max: 12,
    idleTimeoutMillis: 30_000
  });
  // Keep the API process alive when Postgres restarts and idle clients are terminated.
  pool.on('error', (error: Error) => {
    console.warn('[db] pool_client_error', {
      message: error.message,
      code: (error as { code?: unknown }).code ?? null
    });
  });

  const client = await pool.connect();

  try {
    for (const migration of MIGRATIONS) {
      await client.query(migration);
    }
  } finally {
    client.release();
  }

  return pool;
}
