import assert from 'node:assert/strict';
import test from 'node:test';

import {
  buildEnvironmentIosSource,
  normalizeBackendOrigin,
  parseDotEnv,
  parseOriginPort,
  resolveBackendOrigin,
  resolveLocalBackendOrigin,
  writeEnvironmentIos,
} from './write-environment-ios.mjs';

test('normalizeBackendOrigin accepts http and https origins without paths', () => {
  assert.equal(
    normalizeBackendOrigin('https://gameshelf.example.com/'),
    'https://gameshelf.example.com'
  );
  assert.equal(normalizeBackendOrigin('http://192.168.1.10:8080'), 'http://192.168.1.10:8080');
});

test('normalizeBackendOrigin rejects origins with paths or credentials', () => {
  assert.equal(normalizeBackendOrigin('https://gameshelf.example.com/api'), null);
  assert.equal(normalizeBackendOrigin('https://user:pass@gameshelf.example.com'), null);
  assert.equal(normalizeBackendOrigin(''), null);
});

test('parseOriginPort reads explicit and default ports', () => {
  assert.equal(parseOriginPort('http://192.168.0.5:11621'), 11621);
  assert.equal(parseOriginPort('https://prod.example.com'), 443);
  assert.equal(parseOriginPort('http://localhost'), 80);
});

test('resolveBackendOrigin prefers variant-specific keys over BACKEND_ORIGIN', () => {
  const envValues = {
    IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.1.20:8080',
    IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com',
    BACKEND_ORIGIN: 'https://fallback.example.com',
  };

  assert.equal(resolveBackendOrigin('local', envValues), 'http://192.168.1.20:8080');
  assert.equal(resolveBackendOrigin('prod', envValues), 'https://prod.example.com');
});

test('resolveBackendOrigin falls back to BACKEND_ORIGIN', () => {
  assert.equal(
    resolveBackendOrigin('prod', { BACKEND_ORIGIN: 'https://only.example.com/' }),
    'https://only.example.com'
  );
});

test('resolveLocalBackendOrigin composes origin from IOS_LAN_HOST and worktree edge port', () => {
  assert.equal(
    resolveLocalBackendOrigin({ IOS_LAN_HOST: '192.168.0.21' }, { edgePort: 11621 }),
    'http://192.168.0.21:11621'
  );
});

test('resolveLocalBackendOrigin prefers IOS_BACKEND_ORIGIN_LOCAL over composed origin', () => {
  assert.equal(
    resolveLocalBackendOrigin(
      {
        IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.0.21:8080',
        IOS_LAN_HOST: '192.168.0.21',
      },
      { edgePort: 11621 }
    ),
    'http://192.168.0.21:8080'
  );
});

test('resolveLocalBackendOrigin warns when explicit origin port mismatches worktree edge port', () => {
  const warnings = [];

  resolveLocalBackendOrigin(
    { IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.0.21:8080' },
    {
      edgePort: 11621,
      logWarning: (message) => warnings.push(message),
    }
  );

  assert.equal(warnings.length, 1);
  assert.match(warnings[0], /port 8080/);
  assert.match(warnings[0], /edge port is 11621/);
});

test('buildEnvironmentIosSource embeds the resolved backend origin', () => {
  const source = buildEnvironmentIosSource('local', {
    IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.0.5:8080',
  });

  assert.match(source, /const BACKEND_ORIGIN = 'http:\/\/192\.168\.0\.5:8080'/);
  assert.match(source, /production: false/);
  assert.match(source, /emulatorJsDebug: true/);
  assert.match(source, /Generated by scripts\/write-environment-ios\.mjs/);
});

test('buildEnvironmentIosSource composes local origin from LAN host and edge port', () => {
  const source = buildEnvironmentIosSource(
    'local',
    { IOS_LAN_HOST: '192.168.0.21' },
    { edgePort: 11621 }
  );

  assert.match(source, /const BACKEND_ORIGIN = 'http:\/\/192\.168\.0\.21:11621'/);
});

test('writeEnvironmentIos can skip writing to disk', async () => {
  const result = await writeEnvironmentIos('prod', {
    processEnv: { IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com' },
    write: false,
  });

  assert.equal(result.backendOrigin, 'https://prod.example.com');
  assert.match(result.source, /production: true/);
});

test('parseDotEnv ignores comments and parses quoted values', () => {
  assert.deepEqual(
    parseDotEnv(`
# comment
IOS_BACKEND_ORIGIN_PROD="https://prod.example.com"
BACKEND_ORIGIN='http://192.168.1.2:8080'
`),
    {
      IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com',
      BACKEND_ORIGIN: 'http://192.168.1.2:8080',
    }
  );
});
