import assert from 'node:assert/strict';
import test from 'node:test';

import {
  buildEnvironmentIosSource,
  normalizeBackendOrigin,
  parseDotEnv,
  resolveBackendOrigin,
  writeEnvironmentIos,
} from './write-environment-ios.mjs';

test('normalizeBackendOrigin accepts http and https origins without paths', () => {
  assert.equal(
    normalizeBackendOrigin('https://gameshelf.example.com/'),
    'https://gameshelf.example.com'
  );
  assert.equal(normalizeBackendOrigin('http://192.168.1.10:8080'), 'http://192.168.1.10:8080');
});

test('normalizeBackendOrigin rejects origins with paths or credentials', () => {
  assert.equal(normalizeBackendOrigin('https://gameshelf.example.com/api'), null);
  assert.equal(normalizeBackendOrigin('https://user:pass@gameshelf.example.com'), null);
  assert.equal(normalizeBackendOrigin(''), null);
});

test('resolveBackendOrigin prefers variant-specific keys over BACKEND_ORIGIN', () => {
  const envValues = {
    IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.1.20:8080',
    IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com',
    BACKEND_ORIGIN: 'https://fallback.example.com',
  };

  assert.equal(resolveBackendOrigin('local', envValues), 'http://192.168.1.20:8080');
  assert.equal(resolveBackendOrigin('prod', envValues), 'https://prod.example.com');
});

test('resolveBackendOrigin falls back to BACKEND_ORIGIN', () => {
  assert.equal(
    resolveBackendOrigin('prod', { BACKEND_ORIGIN: 'https://only.example.com/' }),
    'https://only.example.com'
  );
});

test('buildEnvironmentIosSource embeds the resolved backend origin', () => {
  const source = buildEnvironmentIosSource('local', {
    IOS_BACKEND_ORIGIN_LOCAL: 'http://192.168.0.5:8080',
  });

  assert.match(source, /const BACKEND_ORIGIN = 'http:\/\/192\.168\.0\.5:8080'/);
  assert.match(source, /production: false/);
  assert.match(source, /emulatorJsDebug: true/);
  assert.match(source, /Generated by scripts\/write-environment-ios\.mjs/);
});

test('writeEnvironmentIos can skip writing to disk', () => {
  const result = writeEnvironmentIos('prod', {
    processEnv: { IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com' },
    write: false,
  });

  assert.equal(result.backendOrigin, 'https://prod.example.com');
  assert.match(result.source, /production: true/);
});

test('parseDotEnv ignores comments and parses quoted values', () => {
  assert.deepEqual(
    parseDotEnv(`
# comment
IOS_BACKEND_ORIGIN_PROD="https://prod.example.com"
BACKEND_ORIGIN='http://192.168.1.2:8080'
`),
    {
      IOS_BACKEND_ORIGIN_PROD: 'https://prod.example.com',
      BACKEND_ORIGIN: 'http://192.168.1.2:8080',
    }
  );
});
